FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src
EXPOSE 80
EXPOSE 443

COPY ["IdentityProvider.Api.csproj", "./"]
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
RUN ls
COPY --from=build /app .
ENTRYPOINT ["dotnet", "IdentityProvider.Api.dll"]