version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: dockerfile
    container_name: aspnet_app
    ports:
      - "8098:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=172.29.3.110;Port=5477;Database=auth;Username=auth;Password=auth_db@1234