# @baseUrl = http://172.29.3.110:8098
# @token = CfDJ8F_wG1kx4sNNoxeTtbH0L0IiGpu_mSHsFM30yj9LpihClO8_DlY5ZpW15eolKcHODp1nJZ_d1gOc339DC25UmT99zjCq5VNdeaB8Yz2UpvaMaKMdm_DoitS0YlLZcqa5ruG0kEJ3s9aLybsvfvG2cjJ9b7q8zHyUxTf3wrwe3DyUYDFI9Jdx-alZJdgdXottkkiUIWPuYF9sPxQ1-_KSgC-q8D9nPMFy8JrTvm5NBE2iRGo3LqArjgUziPZvIx5nKUkSXSqNqWe25w9vxeQJyjUkB58m4zG4CgTbJlSV4fxCd4Sa38V5t8U8VRol9SpEFYrXdrOWWvWyn5c9eAnrEE8CYzH-0ONmB16dsA0_pejwYdxZKY9EE73OCtg84YuICxxLQSGQFWsdW5Tx3CIfOKXdKhYQNDYJqts7x_Bj2Ez8GiTTH9qzVMA1nUD31ld-pbMVjfcild3MFW5XME_jzGlQrMzDd5K0YJT2btGqHHnJdfT3u5fjSnEF8umEZBypoRYqaizD4Wev5oQlrYJpzEH4jij8sxBb80I6dZbozvuK0ndgXaT6605KyGxmApHPeUolK9QTP85sVZGZWs9fseSKbxnySkl1Ol9aYa3vlU5-NSUx7sIme-SiDgBJSxpK9mjtRuXucmUlZk5NGO2wel4

# ### Get User
# GET {{baseUrl}}/userId/
# Authorization: Bearer {{token}}


@baseUrl = http://172.29.3.110:8098/ProjectManagement/api/projects/2
@token = CfDJ8AM0FxZ3SfZCh7i8NqEZhut_tvJqWQVv530YkIlxP_rUOTLj49oy5zQe8UPhhZQEZOe11Gom1gPQC8NT3gVxJBgB3Jjy3DxnYquC8vAU5dmho65CpFht6i1todEZATWkI3sxDdSkxM1OgjU6Yyeb7xguPwwgDnG6aDZQXq9OFixzEMV51OHQVmRYWoXExgyfg66KpHP1MD2p_bRJKL9zdKYvDF0kvu_C35EZLcyEozfj0wGa2vaGVkh35Xy-IDIKmuuE1hGtQwv68B1g5oNbuEB9PXFuxqWtXYZHgE8CphVYl-SaLvL3AmXUqqWcc9Lzy_5HhcnD5YVI22TlAFCl6uOB4brtdbHhXEatIPbzqdEuZzHtTGBBarU6TW4YSjrw6NwRRalRpFW7huzeEAqqbVdvvx1KC5aQnUoV4a5HmCtnMyDdqMR0-nfh3onXUItV1c0P07hMeVfqICdYGLsBnJmlzcyVDTr_OXwRXfbq8LZQa19uWWG74lzSTU-2O136MAkoZpCigr4DR_I4aVR8mvAC0C2QVG7Jev6B64aP94z8i5XEj-HYiixO1TuCkDV_m_W6ZdyiP9MYd-sj-953GHcpImkJW_s2of52rP_I85LbvBj0Jt0rS61kPf_hoMPRkdiwyZnpxvX2WEZ8OygQvgI

### Get User
GET {{baseUrl}}
Authorization: Bearer {{token}}
